-- Books Backup
-- Generated on: 2025-05-22 21:40:50.940657

INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (1, 'Đắc Nhân Tâm', 'Dale Carnegie', 'NXB Tổng hợp TP.HCM', 2016, 3, 'Cuốn sách nổi tiếng về nghệ thuật đối nhân xử thế', 75000.0, '/images/covers/dac-nhan-tam.jpg', '/files/books/dac-nhan-tam.pdf', 320, '2023-01-10 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (2, 'Nhà Giả Kim', 'Paulo Coelho', 'NXB Văn Học', 2017, 6, 'Câu chuyện về hành trình theo đuổi giấc mơ của chàng chăn cừu Santiago', 65000.0, '/images/covers/nha-gia-kim.jpg', '/files/books/nha-gia-kim.pdf', 224, '2023-02-15 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (3, 'Tuổi Trẻ Đáng Giá Bao Nhiêu', 'Rosie Nguyễn', 'NXB Hội Nhà Văn', 2018, 3, 'Cuốn sách về những trải nghiệm, cảm nhận về cuộc sống của tác giả', 80000.0, '/images/covers/tuoi-tre-dang-gia-bao-nhieu.jpg', '/files/books/tuoi-tre-dang-gia-bao-nhieu.pdf', 285, '2023-03-20 00:00:00', '2023-12-15 00:00:00', 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (4, 'Dạy Con Làm Giàu (Tập 1)', 'Robert T. Kiyosaki', 'NXB Trẻ', 2019, 2, 'Sách về tài chính cá nhân và cách dạy con cái về tiền bạc', 90000.0, '/images/covers/day-con-lam-giau.jpg', '/files/books/day-con-lam-giau-tap1.pdf', 240, '2023-04-10 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (5, 'Đời Ngắn Đừng Ngủ Dài', 'Robin Sharma', 'NXB Trẻ', 2020, 3, 'Sách về cách tận dụng thời gian và sống có mục đích', 70000.0, '/images/covers/doi-ngan-dung-ngu-dai.jpg', '/files/books/doi-ngan-dung-ngu-dai.pdf', 256, '2023-05-15 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (6, 'Clean Code', 'Robert C. Martin', 'Prentice Hall', 2008, 8, 'Sách về cách viết code sạch và dễ bảo trì', 120000.0, '/images/covers/clean-code.jpg', '/files/books/clean-code.pdf', 464, '2023-06-20 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (7, 'Trên Đường Băng', 'Tony Buổi Sáng', 'NXB Trẻ', 2017, 3, 'Những bài học, lời khuyên dành cho giới trẻ', 85000.0, '/images/covers/tren-duong-bang.jpg', '/files/books/tren-duong-bang.pdf', 308, '2023-07-10 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (8, 'Marketing 4.0', 'Philip Kotler', 'NXB Trẻ', 2019, 7, 'Cuốn sách về marketing trong kỷ nguyên số', 95000.0, '/images/covers/marketing-4.0.jpg', '/files/books/marketing-4.0.pdf', 336, '2023-08-15 00:00:00', '2024-02-10 00:00:00', 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (9, 'Tôi Thấy Hoa Vàng Trên Cỏ Xanh', 'Nguyễn Nhật Ánh', 'NXB Trẻ', 2015, 5, 'Truyện dài về tuổi thơ của những đứa trẻ vùng quê Việt Nam', 80000.0, '/images/covers/toi-thay-hoa-vang-tren-co-xanh.jpg', '/files/books/toi-thay-hoa-vang-tren-co-xanh.pdf', 376, '2023-09-20 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (10, 'Sapiens: Lược Sử Loài Người', 'Yuval Noah Harari', 'NXB Thế Giới', 2018, 6, 'Cuốn sách về lịch sử phát triển của loài người', 150000.0, '/images/covers/sapiens.jpg', '/files/books/sapiens.pdf', 560, '2023-10-10 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (11, 'Cây Cam Ngọt Của Tôi', 'José Mauro de Vasconcelos', 'NXB Hội Nhà Văn', 2018, 6, 'Tác phẩm nổi tiếng của văn học Brazil', 75000.0, '/images/covers/cay-cam-ngot-cua-toi.jpg', '/files/books/cay-cam-ngot-cua-toi.pdf', 288, '2023-11-15 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (12, 'Người Giàu Có Nhất Thành Babylon', 'George S. Clason', 'NXB Lao Động', 2019, 2, 'Sách về nguyên tắc tài chính cá nhân', 65000.0, '/images/covers/nguoi-giau-co-nhat-thanh-babylon.jpg', '/files/books/nguoi-giau-co-nhat-thanh-babylon.pdf', 208, '2023-12-20 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (13, 'Python Cơ Bản', 'Đỗ Minh Huy', 'NXB Bách Khoa Hà Nội', 2020, 8, 'Sách hướng dẫn học lập trình Python', 110000.0, '/images/covers/python-co-ban.jpg', '/files/books/python-co-ban.pdf', 420, '2024-01-10 00:00:00', '2024-03-15 00:00:00', 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (14, 'Cho Tôi Xin Một Vé Đi Tuổi Thơ', 'Nguyễn Nhật Ánh', 'NXB Trẻ', 2016, 5, 'Tác phẩm văn học về tuổi thơ', 70000.0, '/images/covers/cho-toi-xin-mot-ve-di-tuoi-tho.jpg', '/files/books/cho-toi-xin-mot-ve-di-tuoi-tho.pdf', 264, '2024-02-15 00:00:00', NULL, 1);
INSERT INTO Books (BookID, Title, Author, Publisher, PublishYear, CategoryID, Description, Price, CoverImage, FilePath, PageCount, AddedDate, UpdatedDate, Status) VALUES (15, 'Không Diệt Không Sinh Đừng Sợ Hãi', 'Thích Nhất Hạnh', 'NXB Thế Giới', 2017, 3, 'Sách về triết lý sống của Thiền sư Thích Nhất Hạnh', 85000.0, '/images/covers/khong-diet-khong-sinh.jpg', '/files/books/khong-diet-khong-sinh.pdf', 176, '2024-03-20 00:00:00', NULL, 1);
